/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedGeneratorRouteImport } from './routes/_authenticated.generator'
import { Route as AuthenticatedNpsRouteImport } from './routes/_authenticated.nps'
import { Route as ApiAdminSetPasswordRouteImport } from './routes/api/admin-set-password'
import { Route as ApiGenerateResumeRouteImport } from './routes/api/generate-resume'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as BriefingTokenRouteImport } from './routes/briefing.$token'
import { Route as NpsFormRouteImport } from './routes/nps.form'
import { Route as AuthenticatedTpmIndexRouteImport } from './routes/_authenticated.tpm.index'
import { Route as AuthenticatedTpmCasesRouteImport } from './routes/_authenticated.tpm.cases'
import { Route as AuthenticatedTpmNovoRouteImport } from './routes/_authenticated.tpm.novo'
import { Route as ApiTpmCasesRouteImport } from './routes/api/tpm.cases'
import { Route as ApiTpmFeedbackRouteImport } from './routes/api/tpm.feedback'
import { Route as ApiTpmGenerateRouteImport } from './routes/api/tpm.generate'
import { Route as ApiTpmMatchSectorRouteImport } from './routes/api/tpm.match-sector'
import { Route as ApiTpmParseAgendaRouteImport } from './routes/api/tpm.parse-agenda'
import { Route as ApiTpmReportsRouteImport } from './routes/api/tpm.reports'
import { Route as ApiTpmSharedRouteImport } from './routes/api/tpm.shared'
import { Route as ApiTpmSimulateRouteImport } from './routes/api/tpm.simulate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGeneratorRoute = AuthenticatedGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNpsRoute = AuthenticatedNpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAdminSetPasswordRoute = ApiAdminSetPasswordRouteImport.update({
  id: '/api/admin-set-password',
  path: '/api/admin-set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateResumeRoute = ApiGenerateResumeRouteImport.update({
  id: '/api/generate-resume',
  path: '/api/generate-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingTokenRoute = BriefingTokenRouteImport.update({
  id: '/briefing/$token',
  path: '/briefing/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsFormRoute = NpsFormRouteImport.update({
  id: '/nps/form',
  path: '/nps/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTpmIndexRoute = AuthenticatedTpmIndexRouteImport.update({
  id: '/tpm/',
  path: '/tpm/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTpmCasesRoute = AuthenticatedTpmCasesRouteImport.update({
  id: '/tpm/cases',
  path: '/tpm/cases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTpmNovoRoute = AuthenticatedTpmNovoRouteImport.update({
  id: '/tpm/novo',
  path: '/tpm/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTpmCasesRoute = ApiTpmCasesRouteImport.update({
  id: '/api/tpm/cases',
  path: '/api/tpm/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTpmFeedbackRoute = ApiTpmFeedbackRouteImport.update({
  id: '/api/tpm/feedback',
  path: '/api/tpm/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTpmGenerateRoute = ApiTpmGenerateRouteImport.update({
  id: '/api/tpm/generate',
  path: '/api/tpm/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTpmMatchSectorRoute = ApiTpmMatchSectorRouteImport.update({
  id: '/api/tpm/match-sector',
  path: '/api/tpm/match-sector',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTpmParseAgendaRoute = ApiTpmParseAgendaRouteImport.update({
  id: '/api/tpm/parse-agenda',
  path: '/api/tpm/parse-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTpmReportsRoute = ApiTpmReportsRouteImport.update({
  id: '/api/tpm/reports',
  path: '/api/tpm/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTpmSharedRoute = ApiTpmSharedRouteImport.update({
  id: '/api/tpm/shared',
  path: '/api/tpm/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTpmSimulateRoute = ApiTpmSimulateRouteImport.update({
  id: '/api/tpm/simulate',
  path: '/api/tpm/simulate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/api/admin-set-password': typeof ApiAdminSetPasswordRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/usage': typeof ApiUsageRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/nps/form': typeof NpsFormRoute
  '/tpm/cases': typeof AuthenticatedTpmCasesRoute
  '/tpm/novo': typeof AuthenticatedTpmNovoRoute
  '/api/tpm/cases': typeof ApiTpmCasesRoute
  '/api/tpm/feedback': typeof ApiTpmFeedbackRoute
  '/api/tpm/generate': typeof ApiTpmGenerateRoute
  '/api/tpm/match-sector': typeof ApiTpmMatchSectorRoute
  '/api/tpm/parse-agenda': typeof ApiTpmParseAgendaRoute
  '/api/tpm/reports': typeof ApiTpmReportsRoute
  '/api/tpm/shared': typeof ApiTpmSharedRoute
  '/api/tpm/simulate': typeof ApiTpmSimulateRoute
  '/tpm/': typeof AuthenticatedTpmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/api/admin-set-password': typeof ApiAdminSetPasswordRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/usage': typeof ApiUsageRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/nps/form': typeof NpsFormRoute
  '/tpm/cases': typeof AuthenticatedTpmCasesRoute
  '/tpm/novo': typeof AuthenticatedTpmNovoRoute
  '/api/tpm/cases': typeof ApiTpmCasesRoute
  '/api/tpm/feedback': typeof ApiTpmFeedbackRoute
  '/api/tpm/generate': typeof ApiTpmGenerateRoute
  '/api/tpm/match-sector': typeof ApiTpmMatchSectorRoute
  '/api/tpm/parse-agenda': typeof ApiTpmParseAgendaRoute
  '/api/tpm/reports': typeof ApiTpmReportsRoute
  '/api/tpm/shared': typeof ApiTpmSharedRoute
  '/api/tpm/simulate': typeof ApiTpmSimulateRoute
  '/tpm': typeof AuthenticatedTpmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/generator': typeof AuthenticatedGeneratorRoute
  '/_authenticated/nps': typeof AuthenticatedNpsRoute
  '/api/admin-set-password': typeof ApiAdminSetPasswordRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/usage': typeof ApiUsageRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/nps/form': typeof NpsFormRoute
  '/_authenticated/tpm/cases': typeof AuthenticatedTpmCasesRoute
  '/_authenticated/tpm/novo': typeof AuthenticatedTpmNovoRoute
  '/api/tpm/cases': typeof ApiTpmCasesRoute
  '/api/tpm/feedback': typeof ApiTpmFeedbackRoute
  '/api/tpm/generate': typeof ApiTpmGenerateRoute
  '/api/tpm/match-sector': typeof ApiTpmMatchSectorRoute
  '/api/tpm/parse-agenda': typeof ApiTpmParseAgendaRoute
  '/api/tpm/reports': typeof ApiTpmReportsRoute
  '/api/tpm/shared': typeof ApiTpmSharedRoute
  '/api/tpm/simulate': typeof ApiTpmSimulateRoute
  '/_authenticated/tpm/': typeof AuthenticatedTpmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/generator'
    | '/nps'
    | '/api/admin-set-password'
    | '/api/generate-resume'
    | '/api/usage'
    | '/briefing/$token'
    | '/nps/form'
    | '/tpm/cases'
    | '/tpm/novo'
    | '/api/tpm/cases'
    | '/api/tpm/feedback'
    | '/api/tpm/generate'
    | '/api/tpm/match-sector'
    | '/api/tpm/parse-agenda'
    | '/api/tpm/reports'
    | '/api/tpm/shared'
    | '/api/tpm/simulate'
    | '/tpm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/generator'
    | '/nps'
    | '/api/admin-set-password'
    | '/api/generate-resume'
    | '/api/usage'
    | '/briefing/$token'
    | '/nps/form'
    | '/tpm/cases'
    | '/tpm/novo'
    | '/api/tpm/cases'
    | '/api/tpm/feedback'
    | '/api/tpm/generate'
    | '/api/tpm/match-sector'
    | '/api/tpm/parse-agenda'
    | '/api/tpm/reports'
    | '/api/tpm/shared'
    | '/api/tpm/simulate'
    | '/tpm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/generator'
    | '/_authenticated/nps'
    | '/api/admin-set-password'
    | '/api/generate-resume'
    | '/api/usage'
    | '/briefing/$token'
    | '/nps/form'
    | '/_authenticated/tpm/cases'
    | '/_authenticated/tpm/novo'
    | '/api/tpm/cases'
    | '/api/tpm/feedback'
    | '/api/tpm/generate'
    | '/api/tpm/match-sector'
    | '/api/tpm/parse-agenda'
    | '/api/tpm/reports'
    | '/api/tpm/shared'
    | '/api/tpm/simulate'
    | '/_authenticated/tpm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAdminSetPasswordRoute: typeof ApiAdminSetPasswordRoute
  ApiGenerateResumeRoute: typeof ApiGenerateResumeRoute
  ApiUsageRoute: typeof ApiUsageRoute
  BriefingTokenRoute: typeof BriefingTokenRoute
  NpsFormRoute: typeof NpsFormRoute
  ApiTpmCasesRoute: typeof ApiTpmCasesRoute
  ApiTpmFeedbackRoute: typeof ApiTpmFeedbackRoute
  ApiTpmGenerateRoute: typeof ApiTpmGenerateRoute
  ApiTpmMatchSectorRoute: typeof ApiTpmMatchSectorRoute
  ApiTpmParseAgendaRoute: typeof ApiTpmParseAgendaRoute
  ApiTpmReportsRoute: typeof ApiTpmReportsRoute
  ApiTpmSharedRoute: typeof ApiTpmSharedRoute
  ApiTpmSimulateRoute: typeof ApiTpmSimulateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generator': {
      id: '/_authenticated/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AuthenticatedGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nps': {
      id: '/_authenticated/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof AuthenticatedNpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/admin-set-password': {
      id: '/api/admin-set-password'
      path: '/api/admin-set-password'
      fullPath: '/api/admin-set-password'
      preLoaderRoute: typeof ApiAdminSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-resume': {
      id: '/api/generate-resume'
      path: '/api/generate-resume'
      fullPath: '/api/generate-resume'
      preLoaderRoute: typeof ApiGenerateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/$token': {
      id: '/briefing/$token'
      path: '/briefing/$token'
      fullPath: '/briefing/$token'
      preLoaderRoute: typeof BriefingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps/form': {
      id: '/nps/form'
      path: '/nps/form'
      fullPath: '/nps/form'
      preLoaderRoute: typeof NpsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tpm/': {
      id: '/_authenticated/tpm/'
      path: '/tpm'
      fullPath: '/tpm/'
      preLoaderRoute: typeof AuthenticatedTpmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tpm/cases': {
      id: '/_authenticated/tpm/cases'
      path: '/tpm/cases'
      fullPath: '/tpm/cases'
      preLoaderRoute: typeof AuthenticatedTpmCasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tpm/novo': {
      id: '/_authenticated/tpm/novo'
      path: '/tpm/novo'
      fullPath: '/tpm/novo'
      preLoaderRoute: typeof AuthenticatedTpmNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/tpm/cases': {
      id: '/api/tpm/cases'
      path: '/api/tpm/cases'
      fullPath: '/api/tpm/cases'
      preLoaderRoute: typeof ApiTpmCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tpm/feedback': {
      id: '/api/tpm/feedback'
      path: '/api/tpm/feedback'
      fullPath: '/api/tpm/feedback'
      preLoaderRoute: typeof ApiTpmFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tpm/generate': {
      id: '/api/tpm/generate'
      path: '/api/tpm/generate'
      fullPath: '/api/tpm/generate'
      preLoaderRoute: typeof ApiTpmGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tpm/match-sector': {
      id: '/api/tpm/match-sector'
      path: '/api/tpm/match-sector'
      fullPath: '/api/tpm/match-sector'
      preLoaderRoute: typeof ApiTpmMatchSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tpm/parse-agenda': {
      id: '/api/tpm/parse-agenda'
      path: '/api/tpm/parse-agenda'
      fullPath: '/api/tpm/parse-agenda'
      preLoaderRoute: typeof ApiTpmParseAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tpm/reports': {
      id: '/api/tpm/reports'
      path: '/api/tpm/reports'
      fullPath: '/api/tpm/reports'
      preLoaderRoute: typeof ApiTpmReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tpm/shared': {
      id: '/api/tpm/shared'
      path: '/api/tpm/shared'
      fullPath: '/api/tpm/shared'
      preLoaderRoute: typeof ApiTpmSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tpm/simulate': {
      id: '/api/tpm/simulate'
      path: '/api/tpm/simulate'
      fullPath: '/api/tpm/simulate'
      preLoaderRoute: typeof ApiTpmSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGeneratorRoute: typeof AuthenticatedGeneratorRoute
  AuthenticatedNpsRoute: typeof AuthenticatedNpsRoute
  AuthenticatedTpmCasesRoute: typeof AuthenticatedTpmCasesRoute
  AuthenticatedTpmNovoRoute: typeof AuthenticatedTpmNovoRoute
  AuthenticatedTpmIndexRoute: typeof AuthenticatedTpmIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGeneratorRoute: AuthenticatedGeneratorRoute,
  AuthenticatedNpsRoute: AuthenticatedNpsRoute,
  AuthenticatedTpmCasesRoute: AuthenticatedTpmCasesRoute,
  AuthenticatedTpmNovoRoute: AuthenticatedTpmNovoRoute,
  AuthenticatedTpmIndexRoute: AuthenticatedTpmIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAdminSetPasswordRoute: ApiAdminSetPasswordRoute,
  ApiGenerateResumeRoute: ApiGenerateResumeRoute,
  ApiUsageRoute: ApiUsageRoute,
  BriefingTokenRoute: BriefingTokenRoute,
  NpsFormRoute: NpsFormRoute,
  ApiTpmCasesRoute: ApiTpmCasesRoute,
  ApiTpmFeedbackRoute: ApiTpmFeedbackRoute,
  ApiTpmGenerateRoute: ApiTpmGenerateRoute,
  ApiTpmMatchSectorRoute: ApiTpmMatchSectorRoute,
  ApiTpmParseAgendaRoute: ApiTpmParseAgendaRoute,
  ApiTpmReportsRoute: ApiTpmReportsRoute,
  ApiTpmSharedRoute: ApiTpmSharedRoute,
  ApiTpmSimulateRoute: ApiTpmSimulateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
